### ISSUE TITLE
Linux installer script fails to extract voices for chapter 1

### ISSUE THREAD

**Issue by luziferius** [07th-mod/resources#3]
https://github.com/07th-mod/resources/blob/6cd6f54b0c265060579d38d8970673baf82b98a4/install.sh#L15

The zip archive containing the voices contains all files inside a directory called 'voice' and not 'SE', which the installer expects. This causes the line linked above to fail, which finally results in no voices in-game.

I fixed this on my side by manually extracting Onikakushi-Voices.zip into the StreamingAssets folder.

Voice file archive I used:
`https://github.com/07th-mod/resources/releases/download/Nipah/Onikakushi-Voices.zip`
Link obtained from this table:
`https://github.com/07th-mod/guide/wiki/Higurashi-Part-1---Voice-and-Graphics-Patch#manual-installation-windowslinuxmac`

**Comment by ItaloKnox** [comment]
You are correct, we changed our file structure recently and I forgot to change the Linux installer as well.

I just pushed an update to fix that, next time it'll work fine until we break it again with the lipsync update. I'll be more careful next time. 😛
